### ISSUE TITLE
 error CS0246: The type or namespace name 'AABB' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by castana1962** [skhamis/Unity-ECS-RTS#3]
Hi
I am trying to work with your RTS project in Unity 2019.1b8 and I updated the Mathematics (1.0.0 preview 1) and Entities( 0.0.12 preview 29) packages ( to do it I had that eliminate the Library folder and I opened again the project en 2019.1b8 after that I could do it
and I have 2 errors

Library\PackageCache\com.unity.entities@0.0.12-preview.29\Unity.Mathematics.Extensions\MinMaxAABB.cs(28,52): error CS0246: The type or namespace name 'AABB' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.entities@0.0.12-preview.29\Unity.Mathematics.Extensions\MinMaxAABB.cs(33,41): error CS0246: The type or namespace name 'AABB' could not be found (are you missing a using directive or an assembly reference?)

For it, Could you help me to fix it?
Thanks for your time
Alejandro

**Comment by skhamis** [comment]
Hmmm this is a weird one. You might want to try clone the repository fresh and use the latest beta build for Unity, I tried a fresh copy and no errors.

**Comment by Trojaner** [comment]
Your issues are clearly related to Unity packages, not to this project.
